### ISSUE TITLE
Super admin service fails with transaction step error.

### ISSUE THREAD

**Issue by sleepycat** [canada-ca/tracker#2135]
When launched as a job, the super-admin service fails with the following error:
```
> super-admin@1.0.0 start
> node index.js

Checking for super admin account.
Super admin account, and org not found, creating new account.
/app/src/database/create-super-admin-account.js:37
    throw new Error(
          ^

Error: Transaction step error occurred while creating new super admin account: HttpError: Not Found
    at createSuperAdminAccount (/app/src/database/create-super-admin-account.js:37:11)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async superAdminService (/app/src/super-admin-service.js:29:16)
    at async /app/index.js:24:3
npm notice 
npm notice New minor version of npm available! 7.7.6 -> 7.10.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v7.10.0>
npm notice Run `npm install -g npm@7.10.0` to update!
npm notice 
```

**Comment by sleepycat** [comment]
This is blocking signup too:
```
$ kubectl logs -n api -l app=tracker-api
User 2509012 successfully retrieved domain 8017469.
Transaction step error occurred while user: new.user@tbs-sct.gc.ca attempted to sign up, creating user: HttpError: Not Found
```
