### ISSUE TITLE
Guidance service object is not iterable error

### ISSUE THREAD

**Issue by sleepycat** [canada-ca/tracker#3178]
```python
guidance: Traceback (most recent call last):
  File "/home/guidance/guidance.py", line 173, in <module>
    client = ArangoClient(hosts=DB_URL)
  File "/home/guidance/.local/lib/python3.9/site-packages/arango/client.py", line 58, in __init__
    self._hosts = [host.strip("/") for host in hosts]
TypeError: 'NoneType' object is not iterable
```

**Comment by CADbryon** [comment]
@sleepycat, is this still an issue?

**Comment by h701h** [comment]
@sleepycat, is this still an issue?
